services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sales_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/sales_assistant
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
    depends_on:
      - db
    command: migrate # -url=jdbc:postgresql://db:5432/sales_assistant -schemas=public -user=postgres -password=postgres migrate
    volumes:
      - ./services/db/migrations:/flyway/sql # Your SQL migration files go here

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  api:
    build: ./services/api
    volumes:
      - ./services/api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true # This ensures compatibility for hot-reloading on all systems
    ports:
      - "8000:8000"

volumes:
  postgres_data:
